# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# configuration of the Model Control Plane
model:
  name: "financial_fraud_classifier"
  version: "production"
  license: Apache 2.0
  description: A breast cancer classifier
  tags: ["fraud_detection", "classifier"]