"""
Training Worker Service
=============================================================

This service continuously polls the MySQL database for pending 
retraining jobs generated by the inference API and executes them.
This fully decouples the heavy ML training workload from the 
real-time inference service CPU pool.
"""

import os
import time
import subprocess
import logging
import pymysql
from dotenv import load_dotenv
from pythonjsonlogger import jsonlogger

# Load environment variables
load_dotenv()

# Setup JSON structured logging
logger = logging.getLogger("training_worker")
logger.setLevel(logging.INFO)
logHandler = logging.StreamHandler()
formatter = jsonlogger.JsonFormatter(
    fmt='%(asctime)s %(levelname)s %(name)s %(message)s'
)
logHandler.setFormatter(formatter)
logger.addHandler(logHandler)

MYSQL_HOST = os.getenv("MYSQL_HOST", "127.0.0.1")
MYSQL_PORT = int(os.getenv("MYSQL_PORT", 3306))
MYSQL_USER = os.getenv("MYSQL_USER", "root")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD", "mysqlrootpassword")
MYSQL_DB = os.getenv("MYSQL_DB", "fraud_inference_db")

def get_connection():
    return pymysql.connect(
        host=MYSQL_HOST,
        port=MYSQL_PORT,
        user=MYSQL_USER,
        password=MYSQL_PASSWORD,
        database=MYSQL_DB,
        autocommit=True
    )

def init_job_table():
    """Ensure the retraining_jobs table exists."""
    logger.info("Initializing job table...")
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS retraining_jobs (
                        id INT AUTO_INCREMENT PRIMARY KEY,
                        status VARCHAR(50) DEFAULT 'pending',
                        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                        started_at DATETIME NULL,
                        completed_at DATETIME NULL,
                        error_message TEXT NULL
                    )
                """)
    except Exception as e:
        logger.error(f"Failed to initialize job table: {e}")
        raise

def poll_and_execute():
    """Main polling loop for the worker."""
    logger.info("Worker started. Polling for 'pending' jobs...")
    while True:
        try:
            with get_connection() as conn:
                with conn.cursor() as cur:
                    # Find a pending job
                    cur.execute("SELECT id FROM retraining_jobs WHERE status = 'pending' ORDER BY id ASC LIMIT 1")
                    job = cur.fetchone()

                    if job:
                        job_id = job[0]
                        logger.info(f"Picked up job {job_id}. Marking as running.", extra={"job_id": job_id})
                        cur.execute(
                            "UPDATE retraining_jobs SET status = 'running', started_at = CURRENT_TIMESTAMP WHERE id = %s",
                            (job_id,)
                        )
                        
                        try:
                            # Execute the training pipeline
                            subprocess.run(["python", "run.py", "--training-pipeline"], check=True)
                            
                            # Mark as completed
                            cur.execute(
                                "UPDATE retraining_jobs SET status = 'completed', completed_at = CURRENT_TIMESTAMP WHERE id = %s",
                                (job_id,)
                            )
                            logger.info(f"Job {job_id} completed successfully.", extra={"job_id": job_id})
                        except subprocess.CalledProcessError as e:
                            # Mark as failed
                            cur.execute(
                                "UPDATE retraining_jobs SET status = 'failed', completed_at = CURRENT_TIMESTAMP, error_message = %s WHERE id = %s",
                                (str(e), job_id)
                            )
                            logger.error(f"Job {job_id} failed during execution.", extra={"job_id": job_id, "error": str(e)})

        except Exception as e:
            logger.error("Error connecting to database.", extra={"error": str(e)})
        
        # Wait 10 seconds before polling again
        time.sleep(10)

if __name__ == "__main__":
    init_job_table()
    poll_and_execute()
